### PR TITLE
styling revamp

### PR DESCRIPTION
**Pull request by FireStreaker2**
this pr introduces a lot of changes and fixes, which mainly address styling. it also completes most of the items listed within #5.  the full list of changes is listed below

# changes
in e816646:
* reformat some files via prettier
* change container names to ``.title`` for consistency
* fix spacing issue introduced in #11 

in 94ceb45:
* change some file  names for consistency 
* fix sizing issues on devices with smaller screens
    * change sizing on ``.info p`` in ``Index.module.css``
    * change sizing on navbar elements when screen width is less than ``300px``
    
in c1bab8e:
* migrate to css variables

> note that there are different variables for regular text and the navbar text, that is intentional 

in 871e496:
* update club info/assets
* reformat some stuff in ``[club].jsx``
* apply experimental color palette (not final)

in 871e496 by @HongyiRen2009:
* add info page

in 8db4a87:
* fix issue from previous commit 
* clean up all the other stuff

in 8a519f8:
* resize images
* add club meeting days

in 6d2eccf by @HongyiRen2009 and @TNTiger17:
*  add dropdown menu in navbar
* convert faq boxes to accordions

in 8567905:
* format with prettier
* remove unused package
* add small addition in ``[club].jsx``
* add click effect on contact containers as per @TNTiger17's request

in 2d19863 by @HongyiRen2009:
* finish up info page

in 6c365f3:
* migrate to barrel exports
* format with prettier
* pull from json file in ``Navbar.jsx``

in 946bfd2:
* add option to embed form in contact page

in 78eee74:
* add example ``.env`` file
* readme

# sample images
<details>
  <summary>Show Images</summary>   

sample 1
image

sample 2
image

sample 3
image
</deatails>

### CODE REVIEW

**Review by HongyiRen2009 — DISMISSED** [review]
I think we should change the logo to the light blue one

**Comment by aarnavpbhat** [comment]
Use accordions for FAQs

**Comment by FireStreaker2** [comment]
will do

**Review by TNTiger17 — APPROVED** [review]
This was not made with love but good on you for doing the work i was supposed to do

**Pull request merged**
